import {mountHeoAverage} from './heo2003-average-viewer.mjs';
import {drawFiniteReference} from './finite-crystal-reference.mjs?v=0.24.0-r1';
import {chemicalRegistry,chemicalImage,openChemical} from './chemical-viewer.mjs';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let registryPromise;
let productReferencePromise,productContextsPromise;
async function productIdentity(host,r){
 productContextsPromise??=fetch(new URL('assets/chemical-registry/product-contexts.json',import.meta.url),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Product contexts unavailable');return r.json();});
 const contextual=await productContextsPromise,contexts=contextual.recordContexts[r.record_id]||[],notice=contextual.sourceNotices[r.lineage?.source_group];
 if(contexts.length){const data=await chemicalRegistry(),card=el('article',undefined,'crystal-reference-card'),select=el('select',undefined,'guide-route-select'),view=el('div');select.setAttribute('aria-label','Product specimen or source context');for(const [i,c] of contexts.entries()){const option=el('option',c.label+' · '+c.sample_id);option.value=String(i);select.append(option);}const render=()=>{const c=contexts[Number(select.value)],entry=data.entries.get(c.registry_id);view.replaceChildren();if(entry){view.append(chemicalImage(entry));const b=el('button','Enlarge product representation ↗','molecule-link');b.type='button';b.onclick=()=>openChemical({...entry,caption:c.caption,sourceBindingCaption:c.caption});view.append(b);}view.append(el('p',c.caption),el('p','Phase in this context: '+(c.phase?.value||'Not reported')+(c.phase?.note?' · '+c.phase.note:''),'guide-notice'));for(const e of c.phase?.evidence||[])view.append(el('small',e.source_id+' · '+e.locator));};card.append(el('h3','Product specimens and structural evidence'),select,view);host.append(card);select.onchange=render;render();}
 if(notice)host.append(el('p',notice,'guide-notice'));

 if(!['veinot1997','yao1998','stiger1999','peng1998','shah2001','gerion2001','braun2001','besson2002','dantas2002','yi2002','banerjee2003','schwartz2003','sashchiuk2004','gu2004','nagasaki2004','ribeiro2004','norberg2004'].includes(r.lineage?.source_group))return;
 productReferencePromise??=fetch(new URL('assets/chemical-registry/product-bindings.json',import.meta.url),{cache:'no-store'}).then(r=>r.json());
 const refs=await productReferencePromise,entryId=refs.recordBindings[r.record_id];
 if(entryId){const data=await chemicalRegistry(),entry=data.entries.get(entryId);if(entry){const card=el('article',undefined,'crystal-reference-card');card.append(el('h3',entry.model3dPath?'Product molecular structure':r.lineage?.source_group==='stiger1999'?'Supported nanocrystal structure':['peng1998','shah2001','gerion2001','braun2001','besson2002','dantas2002','yi2002','banerjee2003','schwartz2003','sashchiuk2004','gu2004','nagasaki2004','ribeiro2004','norberg2004'].includes(r.lineage?.source_group)?'Material identity':r.lineage?.source_group==='yao1998'?'Polymer and composite structure':'Surface functionalization'),chemicalImage(entry),el('p',entry.caption||entry.depictionKind));const b=el('button',entry.model3dPath?'Rotate molecular reference ↗':['yao1998','stiger1999','peng1998','shah2001','gerion2001','braun2001','besson2002','dantas2002','yi2002','banerjee2003','schwartz2003','sashchiuk2004','gu2004','nagasaki2004','ribeiro2004','norberg2004'].includes(r.lineage?.source_group)?'Enlarge product representation ↗':'Enlarge surface representation ↗','molecule-link');b.type='button';b.onclick=()=>openChemical(entry);card.append(b);host.append(card);}}
 if(r.lineage?.source_group==='gu2004'&&entryId)host.append(el('p','Original TEM and final-product SAED support the reported FePt and CdS domains. These illustrations show source-labeled composition, not atomic coordinates or an inferred interface. No verified local CdS/FePt CIF is available for this contribution. Intact shells of intermediates 2 and 3 were not successfully isolated.','guide-notice'));
 if(r.lineage?.source_group==='sashchiuk2004'&&entryId)host.append(el('p','Original SAED and HRTEM support rock-salt PbSe. The rotatable unit cell and finite block are constructed ideal references using the rounded reported lattice parameter, not measured sample coordinates, fitted wires or ligand-covered surfaces. Caption and text ratios remain unresolved.','guide-notice'));
 if(r.lineage?.source_group==='schwartz2003'&&entryId)host.append(el('p','The paper supplies TEM and electron-diffraction evidence, but no measured atomic coordinates or refined dopant occupancies. The downloadable ZnO unit cell is an independent undoped host reference, not the Co/Ni-doped specimen or a fitted particle. Surface-bound controls and magnetic aggregates retain their own sample identities.','guide-notice'));
 if(r.lineage?.source_group==='banerjee2003'&&entryId)host.append(el('p','Composite diagrams are illustrative. The paper assigns predominantly wurtzite CdTe with possible zinc-blende character or stacking faults; no refined atomic coordinates, measured junction geometry, SAED pattern or source unit-cell file are supplied. Attached particles, washings and no-tube comparison retain separate sample scopes.','guide-notice'));
 if(r.lineage?.source_group==='yi2002'&&entryId)host.append(el('p','Specimen diagrams are illustrative. The 800 °C powder is assigned tetragonal La2(MoO4)3 with a small unidentified second phase. No refined atomic coordinates, dopant occupancies or measured unit-cell file are supplied. TEM particle sizes, XRD crystallite size and particle-analyzer distributions retain separate specimen/metric scopes.','guide-notice'));
 if(r.lineage?.source_group==='dantas2002'&&entryId)host.append(el('p','Embedded-particle architecture is illustrative. The source supplies AFM topography and model-inferred optical sizes, but no refined PbS phase, atomic lattice parameters or coordinate file. AFM grain heights and ambiguous optical size/radius estimates remain separate; no measured atomic structure download is supplied.','guide-notice'));
 if(r.lineage?.source_group==='besson2002'&&entryId)host.append(el('p','Pore and particle illustrations describe the mesoscopic arrangement. The original HRTEM supports some blende-type CdS 111 fringes; P6₃/mmc and nanometre lattice dimensions describe the mesostructure. Figure 3d is an image Fourier power spectrum, not SAED. No measured atomic coordinates or source CIF are supplied.','guide-notice'));
 if(r.lineage?.source_group==='braun2001'&&entryId)host.append(el('p','Layer-sequence illustrations follow the source-assigned CdS/HgS/CdS architectures. The paper cites tetrahedral CdS and shows schematic wavefunctions, but supplies no measured atomic coordinates, sample CIF, TEM, XRD or SAED pattern. Core-size values conflict between the general preparation and system descriptions; the original figures and source notes preserve that distinction.','guide-notice'));
 if(r.lineage?.source_group==='gerion2001'&&entryId)host.append(el('p','The architecture drawing identifies the core/shell and surface chemistry; it does not assign a uniform shell, particle core count, crystal phase or measured atomic positions. Main-text size distributions and optical data are reproduced below. Announced HRTEM/AFM supporting figures are not available locally; no sample CIF or invented micrograph is supplied.','guide-notice'));
 if(r.lineage?.source_group==='shah2001'&&entryId)host.append(el('p','The supplied article provides original microscopy and reports crystalline metal cores, but supplies no measured atomic coordinates or refined sample CIF. Hexagonal particle packing is an assembly observation, not a bulk crystal phase. Product cards and molecular conformers are reference illustrations.','guide-notice'));
 if(r.lineage?.source_group==='peng1998'&&entryId)host.append(el('p','No measured phase or atomic coordinates are supplied for these specimens. Identity cards do not reconstruct a crystal lattice. The 8.5 nm CdSe TEM specimen and the optical calibration tables retain separate source contexts; no sample CIF is inferred.','guide-notice'));
 if(r.lineage?.source_group==='stiger1999')host.append(el('p','The paper assigns FCC silver using the original SAED pattern and tabulated spacings. No refined Ag/Si interface or measured atomic coordinates are supplied. A verified local Ag crystal reference is unavailable; no sample CIF or atomistic interface is invented. Product diagrams are schematic, and bare-Si controls retain their own identity.','guide-notice'));
 if(r.lineage?.source_group==='veinot1997'&&(r.record_id.includes('-ester-')||r.record_id.endsWith('-qdoh')||r.record_id.endsWith('-characterization')))host.append(el('p','The supplied article does not assign a CdS polymorph or provide atomic coordinates. The surface representation shows a proposed connectivity motif, not a measured particle geometry or ligand count. No sample CIF is available.','guide-notice'));
 if(r.lineage?.source_group==='yao1998'&&!/resin-conditioning|cadmium-loading/.test(r.record_id))host.append(el('p','For the principal samples a and b, the paper assigns cubic zinc blende to the CdS component from X-ray diffraction. It supplies no atomic coordinates or sample CIF. A verified cubic CdS reference structure is not available in this local collection. Polymer motifs and particle cross sections are explanatory representations; they do not reconstruct measured atomic positions.','guide-notice'));
}
const colors={Cd:'#d9af67',Se:'#689db3',O:'#ce6374',Zn:'#6c96ba',In:'#91a3c6',P:'#d4a457',Cs:'#9983bd',Pb:'#6b91aa',Br:'#b78654',Co:'#789baa',Fe:'#c48c59',Ir:'#7993a7',X:'#9575b0'};
export async function mountCrystalReferences(host,r){
 if(!host)return;host.replaceChildren();if(await mountHeoAverage(host,r))return;await productIdentity(host,r);registryPromise??=fetch(new URL('assets/crystal-references/registry.json',import.meta.url),{cache:'no-store'}).then(r=>r.json());const data=await registryPromise;const entries=data.entries.filter(x=>(x.record_ids||[]).includes(r.record_id));if(!entries.length){if(r.lineage?.source_group==='heath1996')host.append(el('h3','Atomic structure data'),el('p','The supplied article reports microscopy and crystallinity evidence but provides no atomic coordinates or measured CIF. A verified Ge reference structure is not available in the current local collection; no downloadable sample structure is inferred from the lattice mismatch.','guide-notice'));return;}
 host.append(el('h3','Reference crystal structures'),el('p','Independent or explicitly constructed bulk references for comparison. The unit cell and extended lattice are illustrative references, not atom-by-atom reconstructions of the synthesized nanocrystal.','guide-notice'));const grid=el('div',undefined,'crystal-reference-grid');host.append(grid);
 for(const ref of entries){const card=el('article',undefined,'crystal-reference-card'),view=el('div',undefined,'crystal-reference-view');view.tabIndex=0;view.setAttribute('aria-label',ref.name+' interactive crystal viewer');card.append(el('h4',ref.name),view,el('small',ref.scope||ref.description));const downloads=el('div',undefined,'protocol-controls');for(const [label,url] of [['Download reference CIF ↓',new URL('assets/crystal-references/'+ref.cifPath,import.meta.url)],['Structure source ↗',ref.sourceUrl]]){const a=el('a',label);a.href=url;downloads.append(a);}card.append(downloads);grid.append(card);
 for(const item of ref.additionalDownloads||[]){const a=el('a',item.label+' ↓');a.href=new URL('assets/crystal-references/'+item.path,import.meta.url);downloads.append(a);}
 if(ref.sourceLinkLabel)downloads.children[1].textContent=ref.sourceLinkLabel+' ↗';
 if(!window.$3Dmol)continue;
 const model=await(await fetch(new URL('assets/crystal-references/'+ref.modelPath+'?sha='+ref.modelSha256,import.meta.url))).json(),v=model.cellVectors;const viewer=$3Dmol.createViewer(view,{backgroundColor:'#f5f9fc'});let extent=1,finiteModel=null;
 const point=(i,j,k)=>({x:i*v[0][0]+j*v[1][0]+k*v[2][0],y:i*v[0][1]+j*v[1][1]+k*v[2][1],z:i*v[0][2]+j*v[1][2]+k*v[2][2]});
 function draw(n){extent=n;viewer.clear();let aa=[];for(let i=0;i<n;i++)for(let j=0;j<n;j++)for(let k=0;k<n;k++){const off=point(i,j,k);for(const a of model.atoms)aa.push({serial:aa.length,elem:a.element??a.elem,x:a.x+off.x,y:a.y+off.y,z:a.z+off.z,properties:a.properties});}viewer.addModel().addAtoms(aa);for(const species of new Set(aa.map(a=>a.elem)))viewer.setStyle({elem:species},{sphere:{radius:species==='X'?.32:species==='O'?.26:.38,color:colors[species]||'#7894a7'}});
 for(let axis=0;axis<3;axis++)for(const b of [0,n])for(const c of [0,n]){const start=[b,c];start.splice(axis,0,0);const end=[...start];end[axis]=n;viewer.addLine({start:point(...start),end:point(...end),color:'#89a1b2',linewidth:1});}
 viewer.zoomTo();viewer.rotate(15,'y');viewer.rotate(-12,'x');viewer.render();}
 draw(1);const controls=el('div',undefined,'protocol-controls'),caption=el('p','','guide-notice');const cellCaption=`${ref.spaceGroup} · a=${model.cell.a}, b=${model.cell.b}, c=${model.cell.c} Å; α=${model.cell.alpha}°, β=${model.cell.beta}°, γ=${model.cell.gamma}°. Drag to rotate; scroll to zoom.`;caption.textContent=cellCaption;for(const [label,n] of [['Unit cell',1],['2 × 2 × 2 lattice',2]]){const b=el('button',label);b.type='button';b.onclick=()=>{draw(n);caption.textContent=cellCaption;};controls.append(b);}card.insertBefore(controls,view);card.append(caption);
 if(ref.finiteModelPath){const b=el('button','Illustrative finite particle');b.type='button';b.onclick=async()=>{try{finiteModel??=await(await fetch(new URL('assets/crystal-references/'+ref.finiteModelPath+'?sha='+ref.finiteModelSha256,import.meta.url))).json();drawFiniteReference(viewer,finiteModel);extent=0;caption.textContent=ref.finiteCaption;}catch(e){caption.textContent='Reference model unavailable: '+e.message;}};controls.append(b);}
 if(ref.mixedOccupancy){const sites=[...new Set(model.atoms.filter(a=>a.mixed_site).map(a=>(a.components||[]).map(c=>c.element+' '+c.occupancy).join(' / ')))];card.append(el('p','Purple markers are statistically mixed Co/Fe sites, not an element X or an ordered assignment. Site occupancies: '+sites.join('; ')+'.','guide-notice'));}
 view.onkeydown=e=>{const turns={ArrowLeft:[-12,'y'],ArrowRight:[12,'y'],ArrowUp:[-12,'x'],ArrowDown:[12,'x']}[e.key];if(turns)viewer.rotate(...turns);else if(e.key==='Home'){if(extent===0)drawFiniteReference(viewer,finiteModel);else draw(extent);}else if(['+','='].includes(e.key))viewer.zoom(1.15);else if(e.key==='-')viewer.zoom(1/1.15);else return;e.preventDefault();viewer.render();};const observer=new ResizeObserver(()=>{if(view.isConnected){viewer.resize();viewer.render();}else{viewer.clear();observer.disconnect();}});observer.observe(view);
 }
}
