import {quantityValue} from './quantity-value.mjs';
import {mountMaterialGuide} from './material-guide.mjs?v=0.25.0-r1';
const $=id=>document.getElementById(id);const params=new URLSearchParams(location.search);let id=params.get('id');
function node(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
function link(text,url){const a=node('a',text);a.href=url;return a;}
function q(value){if(!('unit' in value))return value.value===null?'Not reported':String(value.value);if(value.status==='not_reported'||quantityValue(value)===null)return 'Not reported';return (value.approximate?'≈':'')+(quantityValue(value))+' '+value.unit;}
async function paperCards(data){const host=$('material-papers');host.replaceChildren();const ordered=[...data.papers].sort((a,b)=>b.reviewedRecordIds.length-a.reviewedRecordIds.length);let shown=0;
 function batch(){for(const p of ordered.slice(shown,shown+20)){const c=node('article','','paper-contribution');c.append(node('span',p.fullDocumentReview?.label||(p.reviewStatus==='selected_recipes_reviewed'?'Selected recipe contribution reviewed':p.reviewStatus==='published_benchmark'?'Published benchmark · numeric outcomes':'Indexed literature · recipe contribution unverified'),'atlas-status'));const h=node('h3');h.append(link(p.title||p.doi,'paper.html?id='+p.id));c.append(h,node('p',p.doi+' · '+(p.year||'Year unverified')));const links=node('div','','paper-links');if(p.fullDocumentReview)links.append(link((p.fullDocumentReview.label||'Source document review')+' · original figures →',p.fullDocumentReview.url));links.append(link('Inspect source and review status →','paper.html?id='+p.id),link('Publisher ↗',p.doiUrl));c.append(links);host.append(c);}shown+=20;$('more-papers').hidden=shown>=ordered.length;}
 $('more-papers').addEventListener('click',batch);batch();$('paper-contribution-count').textContent=data.papers.length+' source-reviewed synthesis contributions. Unreviewed title matches are excluded.';
}
try{
 const index=await (await fetch('data/materials-index.json',{cache:'no-store'})).json();if(document.body.dataset.material==='CdSe')id=index.materials.find(m=>m.formula==='CdSe')?.id;
 const entry=index.materials.find(m=>m.id===id);if(!entry)throw Error('Material not found. Select a system from the periodic table.');
 const displayCategories=await(await fetch('data/measurement-display.json')).json();const structural=(m,r)=>Object.hasOwn(displayCategories.record_structural_measurement_ids||{},r.record_id)?displayCategories.record_structural_measurement_ids[r.record_id].includes(m.id):displayCategories.structural_properties.includes(m.property)||displayCategories.structural_property_fragments.some(part=>m.property.includes(part));
 const response=await fetch('data/materials/'+entry.id+'.json',{cache:'no-store'});if(!response.ok)throw Error('Material details are unavailable');const data=await response.json();
 if(document.body.dataset.material!=='CdSe'){
  document.title=data.formula+' · Synthesis, characterization and properties | MatterSyn';$('material-formula').textContent=data.formula;$('material-name').textContent=data.name;$('material-elements').textContent=data.elements.join(' · ');
  $('material-scope-note').textContent=data.scope_note+' '+data.reviewed_records+' reviewed method/variant records; this is not an independent-experiment count.';
  if(data.component_only)$('material-formula').textContent=data.formula+' in heterostructures';
  $('material-dataset').href='dataset.html?material='+encodeURIComponent(data.formula);
  const methods=$('material-methods');methods.replaceChildren();
  for(const r of data.records.filter(r=>r.is_synthesis_route&&r.collection!=='published_benchmark')){const a=link('',r.page_url);a.className='method-card';a.append(node('span',r.method.toUpperCase(),'mini-label'),node('h3',r.title),node('p',`${r.formula} · ${r.year} · ${r.architecture.replaceAll('_',' ')}`),node('span','Open synthesis record →','method-open'));methods.append(a);}
  await mountMaterialGuide($('material-illustrated-guide'),data);
  const ids=(data.evidence_records||data.records).filter(r=>r.collection==='reviewed_literature');const details=await Promise.all(ids.map(async r=>(await fetch('data/records/'+r.record_id+'.json',{cache:'no-store'})).json()));
  for(const [hostId,isStructure] of [['material-structures',true],['material-properties',false]]){const host=$(hostId);host.replaceChildren();let count=0;
   for(const note of data.evidence_scope_notes||[])host.append(node('p',note,'guide-notice'));
   for(const r of details){const measurements=r.measurements.filter(m=>(isStructure?structural(m,r):(Object.hasOwn(displayCategories.record_property_measurement_ids||{},r.record_id)?displayCategories.record_property_measurement_ids[r.record_id].includes(m.id):!structural(m,r))));const products=isStructure&&r.record_type!=='procedure'?r.products:[];if(!measurements.length&&!products.length)continue;const card=node('article','','paper-contribution');const title=node('h3',r.title);card.append(node('span',r.record_type.replaceAll('_',' '),'atlas-status'),title);for(const p of products){card.append(node('p',p.source_sample_label||p.sample_id));for(const key of ['composition','phase','morphology','surface']){const f=p[key];if(f?.value!==null&&f?.value!==undefined)card.append(node('p',key+': '+f.value+' · '+f.status+(f.note?' · '+f.note:'')));}card.append(node('small','Recipe link: '+p.recipe_link.replaceAll('_',' ')));}
    for(const m of measurements){const sample=r.products.find(p=>p.sample_id===m.sample_id);card.append(node('p',(sample?.composition?.value||'Sample composition not assigned')+' · '+(sample?.source_sample_label||m.sample_id)+' · '+m.property.replaceAll('_',' ')+': '+q(m.value)+' · '+m.technique+' · '+m.value.status+(m.value.qualifier?' · '+m.value.qualifier:'')+' · '+(sample?.recipe_link==='explicit'?'Explicit recipe link':'Contextual sample; exact recipe link unresolved')));if(m.conditions)card.append(node('p','Measurement conditions: '+m.conditions,'measurement-conditions'));if(m.value.basis)card.append(node('p','Value basis: '+m.value.basis));const ev=node('details',undefined,'measurement-source');ev.append(node('summary','Measurement evidence'));for(const source of m.evidence||[])ev.append(node('p',source.source_id+' · '+source.locator));card.append(ev);}
    card.append(link('Inspect sample, conditions and sources →','records/'+r.record_id+'.html'));host.append(card);count+=measurements.length+products.length;
   }if(!count)host.append(node('p','No reviewed sample-specific evidence is assigned to this section yet. Consult the source list; indexed titles are not measurement labels.','coverage-note'));
  }
 }
 if(document.body.dataset.material==='CdSe'){
  const represented=new Set(['murray-1993-cdse-method-1','murray-1993-cdse-method-2','peng-2000-cdse-typical','peng-2000-cdse-high-aspect-ratio','nakonechnyi-2017-zb-cdse-core','nakonechnyi-2017-zb-cdse-cds-seeded-growth']);
  const additional=data.records.filter(r=>r.is_synthesis_route&&!represented.has(r.record_id)&&r.collection==='reviewed_literature');
  if(additional.length){const category=node('div',undefined,'method-category');category.append(node('h3','Additional synthesis methods'),node('p','Source-reviewed CdSe and CdSe-containing heterostructure protocols. Each method retains its precursor, structure and property evidence.'));const grid=node('div',undefined,'method-grid');for(const r of additional){const a=link('',r.page_url);a.className='method-card';a.append(node('span',r.method.toUpperCase(),'mini-label'),node('h3',r.title),node('p',r.formula+' · '+r.architecture.replaceAll('_',' ')),node('span','Open synthesis record →','method-open'));grid.append(a);}document.querySelector('#methods').append(category,grid);}
 }
 await paperCards(data);
}catch(e){if(e.message.startsWith('Material not found')){const main=document.querySelector('main');main.replaceChildren();const box=node('section',undefined,'unpublished-material');box.append(node('h1','Material review pending'),node('p','This earlier link came from an unverified literature match. It has been removed from the synthesis atlas until a relevant synthesis contribution is reviewed. This does not mean that synthesis papers do not exist.'),link('Explore verified material pages →','index.html'),node('p',''),link('Search the source library →','library.html'));main.append(box);}else{const host=$('material-scope-note')||$('paper-contribution-count');if(host)host.textContent=e.message;}console.error(e);}
