import {protocols as historicalProtocols,feedback} from './murray-data.mjs';
export {feedback};
export const paper={id:'murray1993',title:'Synthesis and Characterization of Nearly Monodisperse CdE (E = S, Se, Te) Semiconductor Nanocrystallites',authors:'C. B. Murray, D. J. Norris & M. G. Bawendi',year:1993,doi:'10.1021/ja00072a025',url:'https://doi.org/10.1021/ja00072a025',pages:'8706–8715',pdf:'https://bpb-us-e1.wpmucdn.com/sites.mit.edu/dist/9/2055/files/2023/10/ja00072a025.pdf',si:'Not located or verified'};
export const inventory={
 method1:[
 {id:'dimethylcadmium',name:'Dimethylcadmium',formula:'Cd(CH₃)₂',role:'Cadmium precursor',amount:'1.00 mL · 13.35 mmol',note:'0.250 μm filtration and vacuum transfer before use.',group:'Synthesis',source:'pp. 8706–8707'},
 {id:'topse',name:'Trioctylphosphine selenide',formula:'C₂₄H₅₁PSe · TOPSe',role:'Selenium precursor',amount:'10.0 mL of 1.0 M stock · 10.00 mmol',note:'Prepared by dissolving Se shot in TOP; subsequently diluted in solution B.',group:'Synthesis',source:'pp. 8706–8707'},
 {id:'top',name:'Trioctylphosphine',formula:'C₂₄H₅₁P · TOP',role:'Coordinating solvent / stock carrier',amount:'25.0 mL in A + 15.0 mL in B; also the TOPSe stock carrier',note:'Used as purchased. The solvent already in the TOPSe stock is additional to these two charges.',group:'Synthesis',source:'pp. 8706–8707'},
 {id:'topo',name:'Trioctylphosphine oxide',formula:'C₂₄H₅₁OP · TOPO',role:'Heated coordinating medium',amount:'50 g',note:'Distilled fraction collected at 260–300 °C and ≈1 Torr. Reactor drying is a separate operation.',group:'Synthesis',source:'pp. 8706–8707'},
 {id:'selenium',name:'Selenium shot',formula:'Se',role:'Starting material for TOPSe stock',amount:'Mass not reported; stock adjusted to 1.0 M',note:'Electronic grade, 99.99+%. Dissolved in TOP before injection; not an elemental-Se injection.',group:'Synthesis',source:'pp. 8706–8707'},
 {id:'argon',name:'Argon',formula:'Ar',role:'Purge / inert atmosphere',amount:'Periodic flush; ≈1 atm before injection',note:'No flow rate or drybox gas composition is specified.',group:'Synthesis',source:'p. 8707'}
 ],
 method2:[
 {id:'dimethylcadmium',name:'Dimethylcadmium',formula:'Cd(CH₃)₂',role:'Cadmium precursor in the route framework',amount:'Method 2 charge not separately reported',note:'General purification: 0.250 μm filtration and vacuum transfer. Do not import the Method 1 charge as a measured Method 2 value.',group:'Synthesis',source:'pp. 8706–8707'},
 {id:'tms2se',name:'Bis(trimethylsilyl)selenium',formula:'(Me₃Si)₂Se · C₆H₁₈SeSi₂',role:'Selenium precursor replacing TOPSe',amount:'Charge and injection-stock concentration not reported',note:'Prepared by cited literature methods; stored at −35 °C in a drybox.',group:'Synthesis',source:'pp. 8706–8707'},
 {id:'top',name:'Trioctylphosphine',formula:'C₂₄H₅₁P · TOP',role:'Coordinating solvent in the referenced route',amount:'Method 2 volume not separately reported',note:'Method 2 refers back to Method 1 and changes the chalcogen precursor; no complete independent stock recipe is printed.',group:'Synthesis',source:'p. 8707'},
 {id:'topo',name:'Trioctylphosphine oxide',formula:'C₂₄H₅₁OP · TOPO',role:'Coordinating medium in the referenced route',amount:'Method 2 mass not separately reported',note:'General distillation at 260–300 °C, ≈1 Torr. This is purification, not the small-species growth temperature.',group:'Synthesis',source:'pp. 8706–8707'},
 {id:'argon',name:'Argon / airless handling',formula:'Ar',role:'General inert-handling context',amount:'Method 2 gas pressure / flow not separately reported',note:'Do not relabel the −35 °C drybox storage condition as the reaction environment.',group:'Synthesis',source:'pp. 8706–8707'}
 ]
};
export const auxiliaryInventory=[
 {id:'methanol',name:'Methanol',formula:'CH₃OH',role:'Nonsolvent / wash',amount:'20 mL + 25 mL + 50 mL rinse per 10-mL reaction aliquot',note:'Anhydrous. Additional dropwise amount during size selection is not specified.',group:'Isolation and size selection',source:'p. 8707'},
 {id:'1-butanol',name:'1-Butanol',formula:'C₄H₁₀O',role:'Redispersion solvent',amount:'25 mL per 10-mL aliquot; size-selection volume unreported',note:'Anhydrous. Retain clear supernatant after removal of the gray byproduct.',group:'Isolation and size selection',source:'p. 8707'},
 {id:'pyridine',name:'Pyridine',formula:'C₅H₅N',role:'Optional ligand exchange / TEM dispersion',amount:'5–10 mL for ≈50 mg capped crystallites in exchange',note:'Exchange at ≈60 °C. TEM uses a dilute pyridine dispersion; that concentration is unreported.',group:'Optional exchange and characterization',source:'p. 8707'},
 {id:'hexane',name:'Hexane',formula:'C₆H₁₄',role:'Exchange nonsolvent / optical dispersant',amount:'Excess for exchange; optical sample volume unreported',note:'Also an alternative size-selection pair with pyridine. Washed CdSe is dispersed in hexane for optical measurements.',group:'Optional exchange and characterization',source:'p. 8707'},
 {id:'chloroform',name:'Chloroform',formula:'CHCl₃',role:'Alternative size-selection solvent',amount:'Not reported',note:'Listed as an alternative chloroform/methanol pair; not an extra mandatory step.',group:'Optional exchange and characterization',source:'p. 8707'}
];
export const stocks={
 method1:[
 {id:'topse-stock',name:'TOPSe stock',solute:'topse',solvent:'top',amount:'Se shot dissolved in sufficient TOP',concentration:'1.0 M TOPSe · reported',description:'The stock-preparation volume and Se mass are not specified. Elemental Se is converted to the named phosphine-selenide precursor before use.',source:'pp. 8706–8707'},
 {id:'solution-a',name:'Solution A',solute:'dimethylcadmium',solvent:'top',amount:'1.00 mL Me₂Cd (13.35 mmol) + 25.0 mL TOP',concentration:'≈0.513 M Me₂Cd · nominal calculation',description:'13.35 mmol / 26.0 mL, assuming additive liquid volumes. Prepared in the drybox; measured final volume is not given.',source:'p. 8707 · Method 1'},
 {id:'solution-b',name:'Solution B',solute:'topse',solvent:'top',amount:'10.0 mL of 1.0 M TOPSe stock + 15.0 mL TOP',concentration:'0.400 M TOPSe · nominal calculation',description:'10.00 mmol / 25.0 mL, assuming additive volumes. This is the diluted injection component, not the original 1.0 M stock.',source:'p. 8707 · Method 1'},
 {id:'combined',name:'Combined injection mixture',solute:'dimethylcadmium',secondSolute:'topse',solvent:'top',amount:'Solution A + solution B, combined in the drybox',concentration:'Nominal Cd 0.262 M; Se 0.196 M · calculated',description:'Based on the 51 mL sum of component volumes. The paper describes a 50-mL syringe; the discrepancy is unresolved. Molecular panels show components separately and do not imply a measured complex.',source:'p. 8707 · Method 1'}
 ],
 method2:[
 {id:'silyl-injection',name:'Method 2 injection precursor',solute:'tms2se',solvent:'top',amount:'(TMS)₂Se substitutes for TOPSe in the referenced route',concentration:'Concentration and charge not reported',description:'TOP is shown as the coordinating-solvent context inherited by reference, not as a numerically specified stock formulation. Do not transfer the 0.3 M THF preparation below into the Murray injection recipe.',source:'p. 8707 · Method 2'},
 {id:'cited-preparation',name:'Cited 1988 precursor solution',solute:'tms2se',solvent:'thf',amount:'Separate preparation in Steigerwald et al. (1988)',concentration:'≈0.3 M (TMS)₂Se in THF · reported in cited paper',description:'This earlier precursor preparation is its own source record. Murray does not state that its injected stock retains this solvent or concentration. See the preparation and storage records below.',source:'Steigerwald et al. 1988 · p. 3047'}
 ]
};
export const protocols=structuredClone(historicalProtocols);
const titles={synthesis:['Precursor preparation','TOPO drying and thermal stabilization','Preparation of solutions A and B','Rapid precursor injection','Controlled growth and optical monitoring','Aliquot withdrawal'],purification:['Aliquot cooling','Methanol flocculation','Byproduct separation','Nanocrystal reflocculation','Methanol rinse and vacuum drying'],fractionation:['Nanocrystal redispersion','Size-selective precipitation','Repeated fractionation']};
for(const [key,list] of Object.entries(titles))protocols[key].steps.forEach((step,i)=>step.title=list[i]);
protocols.synthesis.steps[0].description='Prepare the 1.0 M TOPSe stock by dissolving electronic-grade selenium shot in TOP. The injected selenium reagent is TOPSe in solution, not a separate charge of Se shot. TOPO distillation and dimethylcadmium purification are separate preparative operations.';
protocols.method2={note:'CdSe Method 2 · partial route specification. The paper replaces the Method 1 chalcogen precursor with (TMS)₂Se. Its ≈100 °C small-species variant is explicit; a complete independent CdSe charge, timing and general temperature program are not supplied.',steps:[
 {tab:'Precursor',title:'Silyl-selenium precursor preparation and storage',description:'Use the literature-prepared bis(trimethylsilyl)selenium precursor. Murray reports storage at −35 °C in a drybox. Refer to the separate cited precursor preparation; that source does not supply the missing Murray injection-stock composition.',fields:[['Selenium source','(TMS)₂Se'],['Storage','−35 °C · drybox'],['Preparation references','Murray references 3a and 4'],['Injection-stock concentration','Not reported']],source:'PP. 8706–8707'},
 {tab:'Route',title:'Chalcogen precursor substitution',description:'Method 2 replaces phosphine-chalcogenide reagents with silyl-chalcogenide reagents in the Method 1 framework. For CdSe, (TMS)₂Se replaces TOPSe. The paper does not repeat a full numerical CdSe formulation.',fields:[['Cadmium source','Dimethylcadmium · referenced route'],['Selenium source','(TMS)₂Se instead of TOPSe'],['Charge / injection volume','Not separately reported'],['General CdSe growth conditions','Not separately reported']],source:'P. 8707 · METHOD 2'},
 {tab:'Small species',title:'Low-temperature small-species variant',description:'The smallest CdS, CdSe and CdTe species, approximately 12 Å (1.2 nm), are produced with injection and growth at approximately 100 °C. The separate 290–320 °C growth range in the same paragraph applies to CdS and must not be assigned to CdSe.',fields:[['Injection temperature','≈100 °C'],['Growth temperature','≈100 °C'],['Smallest reported species','≈1.2 nm'],['Duration / reagent quantities','Not reported']],source:'P. 8707 · METHOD 2'}
]};
protocols.exchange={note:'Optional surface exchange · a separate post-synthesis branch. It changes dispersibility and surface derivatization; it is not an obligatory step in Method 1 or Method 2.',steps:[
 {tab:'Pyridine',title:'Pyridine dispersion and ligand exchange',description:'Heat TOP/TOPO-capped nanocrystals with excess pyridine to gradually disperse them. The paper does not specify an exact exchange duration or a measured bound-ligand composition.',fields:[['Capped nanocrystals','≈50 mg'],['Pyridine','5–10 mL'],['Temperature','≈60 °C'],['Duration','Not reported']],source:'P. 8707 · SURFACE EXCHANGE'},
 {tab:'Hexane',title:'Hexane flocculation and recovery',description:'Add excess hexane, then isolate the flocculated crystallites by centrifugation. The hexane volume and centrifugation settings are not reported.',fields:[['Nonsolvent','Excess hexane'],['Keep','Crystallite flocculate'],['Hexane volume','Not reported'],['Speed / duration','Not reported']],source:'P. 8707 · SURFACE EXCHANGE'},
 {tab:'Repeat',title:'Repeated surface exchange',description:'Repeat dispersion in pyridine and flocculation with hexane. The resulting crystallites disperse readily in pyridine, methanol and aromatic solvents, but no longer in aliphatic solvents.',fields:[['Repeat','Pyridine dispersion / hexane flocculation'],['Cycle count','A number of times; exact count unreported'],['Observed outcome','Changed solvent dispersibility'],['Surface composition','Not quantitatively established']],source:'P. 8707 · SURFACE EXCHANGE'}
]};
