export const sourceUrl='https://doi.org/10.1021/ja00072a025';
export const sampleRecords={tem6:{name:'A slightly prolate quantum dot.',long:3.5,short:3.0,source:'FIGURE 6 · P. 8710',method:'TEM: long axis ±5%; short axis ±6%',shape:'dot'}};
export const protocols={
 synthesis:{note:'Method 1 · CdSe only. This sequence uses the original TOPSe route. CdTe, silyl-precursor Method 2 and pyridine surface exchange are separate procedures.',steps:[
 {tab:'Materials',title:'Start with the reported materials.',description:'The authors use airless handling. Selenium shot is dissolved in TOP to prepare a 1.0 M TOPSe stock. TOPO and dimethylcadmium are purified before use; these preparative conditions are distinct from the reaction itself.',fields:[['TOPSe stock','1.0 M in trioctylphosphine'],['TOPO purification','Distilled fraction: 260–300 °C at ≈1 Torr'],['Dimethylcadmium purification','0.250 µm filtration + vacuum transfer'],['Atmosphere','Standard airless procedures']],source:'PP. 8706–8707'},
 {tab:'Hot bath',title:'Dry, degas and heat the TOPO.',description:'Dry and degas the coordinating medium with periodic argon flushing. Then stabilize the bath near 300 °C under argon before injection.',fields:[['TOPO charge','50 g'],['Drying / degassing','≈200 °C · ≈1 Torr · ≈20 min'],['Gas treatment','Periodically flush with argon'],['Before injection','≈300 °C · ≈1 atm argon']],source:'P. 8707 · METHOD 1'},
 {tab:'A + B',title:'Prepare two solutions in the drybox.',description:'Combine solutions A and B and load the mixture into the reported 50-mL syringe. The nominal component volumes add to 51 mL; the paper does not resolve that discrepancy. The amounts are preserved as written.',fields:[['Solution A','1.00 mL Me₂Cd (13.35 mmol) + 25.0 mL TOP'],['Solution B','10.0 mL 1.0 M TOPSe (10.00 mmol) + 15.0 mL TOP'],['Cd : Se feed ratio','1.335 : 1 (calculated from mmol)'],['Syringe / nominal volume','50 mL reported / 51 mL arithmetic sum']],source:'P. 8707 · METHOD 1'},
 {tab:'Inject',title:'Create a short burst of nuclei.',description:'Remove the heat and deliver the combined precursor mixture in a single rapid injection through a rubber septum into vigorously stirred TOPO. The paper reports a yellow/orange solution and a sudden temperature drop.',fields:[['Before → after injection','≈300 → ≈180 °C'],['Addition','Single rapid injection; duration not specified'],['Initial absorption feature','440–460 nm'],['Visible observation','Deep yellow/orange solution']],source:'P. 8707 · METHOD 1'},
 {tab:'Grow',title:'Let the spectrum guide growth.',description:'Restore heating and gradually raise the temperature. Monitor absorption every 5–10 minutes. Lower the temperature when the size distribution spreads; increase it when growth appears to stop. The authors describe a few hours of steady growth, not a fixed time for each size.',fields:[['Initial growth range','230–260 °C'],['Sampling interval','5–10 min'],['Control','Adjust temperature from absorption spectra'],['Duration','A few hours; no fixed size–time schedule']],source:'PP. 8707–8708'},
 {tab:'Withdraw',title:'Take a sample when the target is reached.',description:'When the desired absorption characteristics appear, transfer a portion by cannula and store it in a vial. Method 1 reports a series of sizes from roughly 15 to 115 Å from one preparation. The purification procedure below begins with a 10-mL portion.',fields:[['Endpoint','Desired absorption characteristics'],['Reported size range','≈1.5–11.5 nm (major axis)'],['Sampling operation','Cannula transfer to a vial'],['Next branch','Purify a 10-mL reaction aliquot']],source:'P. 8707 · METHOD 1'}]},
 purification:{note:'Isolation and purification · all amounts below refer to a 10-mL reaction aliquot. Fraction identity matters: first keep the flocculate, then keep the clear liquid after removing gray byproducts.',steps:[
 {tab:'Cool',title:'Work with a 10-mL portion.',description:'Remove a reaction aliquot by cannula and cool it to slightly above the melting point of TOPO. This is a sample workup, not the entire synthesis batch.',fields:[['Reaction aliquot','10 mL'],['Cooling endpoint','≈60 °C'],['Material tracked','TOP/TOPO-capped CdSe in growth medium'],['Cooling time','Not reported']],source:'P. 8707 · ISOLATION'},
 {tab:'Flocculate',title:'Collect the first flocculate.',description:'Add anhydrous methanol to reversibly flocculate the nanocrystals. Separate the flocculate from the supernatant by centrifugation and retain the flocculate for redispersion.',fields:[['Methanol addition','20 mL, anhydrous'],['Separation','Centrifugation'],['Keep','Nanocrystal-containing flocculate'],['Centrifuge speed / time','Not reported']],source:'P. 8707 · ISOLATION'},
 {tab:'Clarify',title:'Now keep the clear liquid.',description:'Disperse the flocculate in anhydrous 1-butanol and centrifuge again. The nanocrystals remain in the optically clear supernatant; the gray precipitate contains mostly elemental Cd and Se byproducts and is discarded.',fields:[['1-Butanol addition','25 mL, anhydrous'],['Keep','Clear nanocrystal supernatant'],['Discard','Gray Cd/Se-rich precipitate'],['Centrifuge speed / time','Not reported']],source:'P. 8707 · ISOLATION'},
 {tab:'Reprecipitate',title:'Remove excess coordinating solvent.',description:'Add anhydrous methanol to the retained clear supernatant to flocculate the nanocrystals again and remove excess TOP and TOPO.',fields:[['Methanol addition','25 mL, anhydrous'],['Product fraction','Nanocrystal flocculate'],['Purpose','Remove excess TOP / TOPO'],['Addition rate','Not reported']],source:'P. 8707 · ISOLATION'},
 {tab:'Rinse & dry',title:'Isolate the capped nanocrystal powder.',description:'Rinse the flocculate with methanol and vacuum-dry it. The reported approximate product mass belongs to this 10-mL aliquot and includes the TOP/TOPO cap; it is not a whole-batch yield or a bare-CdSe mass.',fields:[['Final methanol rinse','50 mL'],['Drying','Under vacuum; time / temperature unspecified'],['Reported isolated product','≈300 mg TOP/TOPO-capped CdSe'],['Mass basis','From a 10-mL reaction aliquot']],source:'P. 8707 · ISOLATION'}]},
 fractionation:{note:'Size-selective precipitation · a separate refinement after purification. The paper gives an observed endpoint, not a fixed methanol volume or a universal number of cycles.',steps:[
 {tab:'Disperse',title:'Begin with a clear dispersion.',description:'Disperse purified nanocrystals in anhydrous 1-butanol until the dispersion is optically clear.',fields:[['Input','Purified capped nanocrystals'],['Solvent','Anhydrous 1-butanol'],['Initial state','Optically clear'],['Concentration / volume','Not reported']],source:'P. 8707 · SIZE SELECTION'},
 {tab:'Select',title:'Enrich the larger particles.',description:'Add anhydrous methanol dropwise until opalescence persists with stirring or sonication. Centrifugation separates a flocculate enriched in the largest crystallites from the remaining supernatant.',fields:[['Nonsolvent','Anhydrous methanol, dropwise'],['Endpoint','Persistent opalescence'],['Keep for this branch','Large-particle-enriched precipitate'],['Methanol volume / centrifugation','Not reported']],source:'PP. 8707–8708'},
 {tab:'Repeat',title:'Repeat until the spectrum stops sharpening.',description:'Redisperse the precipitate in 1-butanol and repeat size-selective precipitation. Figure 1 illustrates a particular sample shifting from about 35 Å ±10% to 37 Å ±5%; it does not define a cycle count for every preparation.',fields:[['Stopping criterion','No further absorption sharpening'],['Figure 1 starting sample','≈3.5 nm ±10%'],['Figure 1 selected sample','≈3.7 nm ±5%'],['Scope','Separate Figure 1 example; not the TEM model']],source:'P. 8708 · FIGURE 1'}]}
};
export const moleculeNotes={
 topo:{head:'Phosphine oxide head group',text:'TOPO is the hot coordinating medium and part of the reported particle cap. Highlighting identifies the free molecule’s P–O group, not a measured surface-binding geometry.'},
 top:{head:'Phosphine coordination center',text:'Trioctylphosphine dissolves and carries the precursors. This is TOP with eight-carbon chains; it is distinct from the tributylphosphine used in the 2000 Alivisatos example.'},
 topse:{head:'Phosphine selenide head group',text:'The authors prepare a 1.0 M TOPSe stock by dissolving selenium shot in TOP. This molecular reference represents the named precursor; it is not a complete model of the reacting solution. The illustrative 3D geometry has not been force-field minimized.'},
 dimethylcadmium:{head:'Cadmium precursor',text:'Dimethylcadmium supplies cadmium. Its displayed CH₃–Cd–CH₃ formula is a connectivity schematic, not a 3D model inferred from a disconnected ionic database record.'},
 methanol:{head:'Alcohol group · nonsolvent',text:'Anhydrous methanol induces flocculation during isolation and size selection. It is a workup reagent, not part of the injected precursor stock.'},
 '1-butanol':{head:'Alcohol group · dispersing solvent',text:'Anhydrous 1-butanol redisperses the capped nanocrystals and is paired with methanol for size-selective precipitation.'},
 selenium:{head:'Elemental starting material',text:'Electronic-grade selenium shot is dissolved in TOP to make the TOPSe stock. The separate trigonal reference shown here does not establish the shot’s allotrope or represent dissolved selenium.'}
};
export const feedback={
 broad:{title:'Lower the growth temperature.',text:'The authors reduce temperature when the size distribution begins to spread, as inferred from absorption spectra.',label:'Distribution broadens'},
 stalled:{title:'Increase the growth temperature.',text:'When growth appears to stop, the authors increase temperature to maintain steady growth. No fixed temperature increment is specified.',label:'Growth slows or stops'},
 target:{title:'Withdraw a portion by cannula.',text:'Once the desired absorption characteristics are reached, transfer a portion into a vial. A universal target wavelength or size–time curve is not supplied.',label:'Target spectrum reached'}
};
