const stages = [
 {title:'Start with the cadmium mixture.',description:'Combine cadmium oxide, myristic acid and 1-octadecene. Myristic acid provides the original ligand chemistry; oleic acid enters later during workup.',fields:[['Cadmium oxide','0.5 mmol'],['Myristic acid','1.6 mmol'],['1-Octadecene (ODE)','10 mL'],['Output','Initial reaction mixture']]},
 {title:'Heat until everything dissolves.',description:'Heat the mixture under the reported ambient conditions until total dissolution at 260 °C. The paper specifies an endpoint, rather than a heating ramp or hold time.',fields:[['Dissolution temperature','260 °C'],['Environment','Ambient conditions'],['Endpoint','Total dissolution'],['Ramp / duration','Not reported']]},
 {title:'Add the selenium dispersion.',description:'Swiftly add black selenium powder dispersed in 1-octadecene to the cadmium solution. “Swiftly” is qualitative: the paper does not quantify the addition time.',fields:[['Selenium powder','0.24 mmol'],['Carrier solvent','1-Octadecene'],['Dispersion volume','Not reported'],['Addition','Swift; duration not reported']]},
 {title:'Let the cores grow.',description:'Allow five minutes of reaction after the selenium addition. The measured temperature change during injection and recovery is not reported; 260 °C is the preceding dissolution temperature.',fields:[['Reaction time','5 min after addition'],['Material','CdSe core QDs'],['Temperature trajectory','Not reported'],['Next event','Water-bath quench']]},
 {title:'Quench. Separate. Keep the pellet.',description:'Stop the reaction using a water bath. Add 2-propanol to precipitate the QDs, then centrifuge and retain the pellet. The relative centrifugal force is specified, but the duration is not.',fields:[['Quench','Water bath'],['2-Propanol','1:1 volume vs reaction mixture'],['Centrifugation','3000 g (not rpm)'],['Retained fraction','QD pellet']]},
 {title:'Give the surface a new ligand.',description:'Redisperse the pellet in toluene and oleic acid. The authors use this step to replace the original myristate ligands with oleate ligands.',fields:[['Toluene','1 mL'],['Oleic acid','1 mL'],['Surface change','Myristate → oleate'],['Exchange duration','Not reported']]},
 {title:'Purify the cores three times.',description:'Before seeded growth, purify the core solution three times using toluene and methanol as the solvent/nonsolvent pair. This page stops at the CdSe cores; shell growth is a separate recipe.',fields:[['Toluene / methanol','1 mL / 1 mL per cycle'],['Repeat count','3 cycles'],['Centrifugation','3000 g; duration not reported'],['Final storage','Solvent / volume not reported']]}
];
let currentStep=0;
function showStep(index){currentStep=index;document.querySelectorAll('[data-step]').forEach(b=>{const active=Number(b.dataset.step)===index;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});const s=stages[index];document.getElementById('step-kicker').textContent='STAGE '+String(index+1).padStart(2,'0')+' / 07';document.getElementById('step-title').textContent=s.title;document.getElementById('step-description').textContent=s.description;document.getElementById('step-fields').innerHTML=s.fields.map(([label,value])=>'<div class="field'+(value.includes('Not reported')?' missing':'')+'"><label>'+label+'</label><span>'+value+'</span></div>').join('');document.getElementById('next-step').textContent=index===6?'Start again ↺':'Next stage →';}
document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>showStep(Number(b.dataset.step))));
document.getElementById('next-step').addEventListener('click',()=>showStep((currentStep+1)%7));showStep(0);
const molecularInfo={
 myristic:{id:'myristic-acid',group:'Carboxylic acid head group',description:'1.6 mmol in the starting mixture. The acid participates in cadmium precursor chemistry; the authors identify myristate as the original QD surface ligand. Shown here as the free acid.'},
 oleic:{id:'oleic-acid',group:'Carboxylic acid head group',description:'1 mL during ligand exchange after isolation. Oleate replaces myristate on the QD surface. The 3D model shows free oleic acid, before deprotonation and binding.'},
 ode:{id:'1-octadecene',group:'Terminal carbon–carbon double bond',description:'10 mL as the reaction medium, plus an unspecified amount in the selenium dispersion. The pink atoms mark the terminal alkene on this long hydrocarbon chain.'},
 ipa:{id:'2-propanol',group:'Alcohol group',description:'Added at a 1:1 volume ratio relative to the reaction mixture to precipitate the QDs. The polar hydroxyl group is highlighted.'},
 toluene:{id:'toluene',group:'Aromatic ring',description:'1 mL for ligand exchange, then 1 mL per purification cycle. Toluene serves as a nonpolar redispersion solvent. Pink marks the aromatic ring, a structural motif.'},
 methanol:{id:'methanol',group:'Alcohol group',description:'1 mL per purification cycle, paired with toluene. Methanol is the nonsolvent in this workup; its hydroxyl group is highlighted.'},
 cdo:{id:'cdo-rocksalt',group:'Rock-salt crystal lattice',description:'0.5 mmol as the cadmium precursor. CdO is an extended ionic solid, not an isolated Cd–O molecule. This reference lattice uses a = 4.6963 Å from COD 9006671.'},
 selenium:{id:'selenium-trigonal',group:'A reference for solid selenium',description:'0.24 mmol black powder dispersed in ODE. The paper does not specify the powder allotrope. This is a trigonal selenium reference with helical chains, not an identification of the reagent phase.'}
};
let moleculeViewer,crystalViewer,molecules=[],solidModels={},crystalReference,selectedMolecule='myristic';
const molecularColors={C:'#728399',H:'#d9e1ea',O:'#e36d7c',N:'#527fea',Cd:'#159eab',Se:'#e3ad51'};
function atomData(data){const atoms=data.atoms.map((a,i)=>({index:i,serial:i,elem:a.element,x:a.x,y:a.y,z:a.z,bonds:[],bondOrder:[]}));data.bonds.forEach(b=>{atoms[b.a].bonds.push(b.b);atoms[b.a].bondOrder.push(b.order);atoms[b.b].bonds.push(b.a);atoms[b.b].bondOrder.push(b.order)});return atoms;}
function showMolecule(key){const meta=molecularInfo[key];if(!meta)return;selectedMolecule=key;const solid=solidModels[key],data=solid?solid.displayModel:molecules.find(d=>d.id===meta.id);if(!data||!moleculeViewer)return;moleculeViewer.removeAllModels();const model=moleculeViewer.addModel();model.addAtoms(atomData(data));const highlight=!solid&&document.getElementById('highlight').checked,highlighted=new Set(solid?[]:data.functionalGroups[0].atomIndices);const colorfunc=a=>highlight&&highlighted.has(a.index)?'#e57191':molecularColors[a.elem]||'#7b8ea3';moleculeViewer.setStyle({}, {stick:{radius:.105,colorfunc},sphere:{scale:.27,colorfunc}});if(highlight)moleculeViewer.addStyle({index:[...highlighted]},{sphere:{scale:.34,color:'#e57191'}});moleculeViewer.zoomTo();moleculeViewer.rotate(15,'y');moleculeViewer.rotate(-15,'z');moleculeViewer.zoom(.92);moleculeViewer.render();document.getElementById('molecule-name').textContent=solid?(key==='cdo'?'Cadmium oxide · CdO':'Selenium · Se'):data.name;document.getElementById('group-name').textContent=meta.group;document.getElementById('group-description').textContent=meta.description;document.getElementById('molecule-status').classList.add('hidden');document.querySelector('#molecule-name + .model-badge').textContent=solid?'REFERENCE LATTICE':'PUBCHEM CONFORMER';document.querySelector('.toggle-label').hidden=!!solid;document.querySelector('.element-legend').innerHTML=solid?(key==='cdo'?'<span><i class="cd"></i>Cadmium</span><span><i class="functional"></i>Oxygen</span>':'<span><i class="se"></i>Selenium</span>'):'<span><i class="carbon"></i>Carbon</span><span><i class="hydrogen"></i>Hydrogen</span><span><i class="functional"></i>'+(highlight?'Highlighted group':'Oxygen (if present)')+'</span>';document.querySelectorAll('[data-molecule]').forEach(b=>{const active=b.dataset.molecule===key;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});document.getElementById('more-reagents').value=['ipa','toluene','methanol','cdo','selenium'].includes(key)?key:'';}
function crystalAtoms(){const a=crystalReference.a,atoms=[];for(let i=-3;i<=2;i++)for(let j=-3;j<=2;j++)for(let k=-3;k<=2;k++)for(const f of crystalReference.fractionalAtoms){const x=a*(i+f.x),y=a*(j+f.y),z=a*(k+f.z);if(Math.hypot(x,y,z)<=15)atoms.push({elem:f.element,x,y,z,bonds:[],bondOrder:[]});}atoms.forEach((v,i)=>{v.serial=i;v.index=i;for(let j=0;j<i;j++){const w=atoms[j],distance=Math.hypot(v.x-w.x,v.y-w.y,v.z-w.z);if(v.elem!==w.elem&&distance>2.5&&distance<2.75){v.bonds.push(j);v.bondOrder.push(1);w.bonds.push(i);w.bondOrder.push(1)}}});return atoms;}
function setCrystalStyle(style){if(!crystalViewer)return;const colorfunc=a=>a.elem==='Cd'?'#159eab':'#e3ad51';crystalViewer.setStyle({},style==='space'?{sphere:{scale:.85,colorfunc}}:{sphere:{scale:.29,colorfunc},stick:{radius:.09,color:'#b6c8ce'}});crystalViewer.render();document.querySelectorAll('[data-style]').forEach(b=>{b.classList.toggle('active',b.dataset.style===style);b.setAttribute('aria-pressed',String(b.dataset.style===style))});}
function resetCrystal(){if(!crystalViewer)return;crystalViewer.zoomTo();crystalViewer.rotate(65,'x');crystalViewer.rotate(25,'y');crystalViewer.rotate(20,'z');crystalViewer.zoom(.9);crystalViewer.render();}
document.querySelectorAll('[data-molecule]').forEach(b=>b.addEventListener('click',()=>showMolecule(b.dataset.molecule)));
document.getElementById('more-reagents').addEventListener('change',e=>{if(e.target.value)showMolecule(e.target.value)});
document.getElementById('highlight').addEventListener('change',()=>showMolecule(selectedMolecule));
document.getElementById('reset-molecule').addEventListener('click',()=>showMolecule(selectedMolecule));
document.getElementById('reset-crystal').addEventListener('click',resetCrystal);
document.querySelectorAll('[data-style]').forEach(b=>b.addEventListener('click',()=>setCrystalStyle(b.dataset.style)));
document.querySelectorAll('[role="tablist"]').forEach(list=>list.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const tabs=[...list.querySelectorAll('[role="tab"]')];const active=tabs.indexOf(document.activeElement);if(active<0)return;event.preventDefault();let next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(active+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();tabs[next].click();}));
async function initialize(){try{if(!window.$3Dmol)throw new Error('The 3D viewer could not be loaded.');const responses=await Promise.all(['molecular-structures.json','crystal-reference.json','cdo-reference.json','selenium-reference.json'].map(file=>fetch('assets/'+file)));if(responses.some(r=>!r.ok))throw new Error('Structure coordinates could not be loaded.');const data=await Promise.all(responses.map(r=>r.json()));molecules=data[0].filter(d=>d.id!=='oleylamine');crystalReference=data[1];solidModels={cdo:data[2],selenium:data[3]};moleculeViewer=$3Dmol.createViewer(document.getElementById('molecule-viewer'),{backgroundColor:'#f8faff',antialias:true});crystalViewer=$3Dmol.createViewer(document.getElementById('crystal-viewer'),{backgroundColor:'#f5f9fb',antialias:true});showMolecule(selectedMolecule);const model=crystalViewer.addModel();model.addAtoms(crystalAtoms());setCrystalStyle('ball');resetCrystal();document.getElementById('crystal-status').classList.add('hidden');document.getElementById('source-links').innerHTML=molecules.map(d=>'<a href="'+d.source+'" target="_blank" rel="noopener noreferrer">'+d.name+' ↗</a>').join('')+'<a href="https://doi.org/10.1063/1.101033" target="_blank" rel="noopener noreferrer">CdSe lattice parameter ↗</a><a href="https://www.crystallography.net/cod/9006671.html" target="_blank" rel="noopener noreferrer">CdO reference ↗</a><a href="https://www.crystallography.net/cod/9012501.html" target="_blank" rel="noopener noreferrer">Selenium reference ↗</a>';const resize=new ResizeObserver(()=>{moleculeViewer.resize();moleculeViewer.render();crystalViewer.resize();crystalViewer.render()});resize.observe(document.getElementById('molecule-viewer'));resize.observe(document.getElementById('crystal-viewer'));}catch(error){document.querySelectorAll('.viewer-status').forEach(el=>{el.textContent=error.message+' Recipe details remain available.';el.classList.remove('hidden')});console.error(error);}}
const flask=document.getElementById('flask-art');flask.addEventListener('load',()=>{flask.hidden=false;document.querySelector('.apparatus-placeholder').hidden=true});flask.src='assets/source-links/bd6465fd76a83e5c26dc0a3e.svg';
initialize();


