import {mountSourceSections} from './source-evidence.mjs?v=0.27.0-r1';
const $=id=>document.getElementById(id);
function node(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
function link(text,href){const a=node('a',text);a.href=href;return a;}
function human(x){return String(x).replaceAll('_',' ');}
function list(v){const ul=node('ul');for(const x of v||[])ul.append(node('li',typeof x==='object'?Object.entries(x).map(([k,v])=>human(k)+': '+format(v)).join(' · '):x));return ul;}
function format(v){if(v===null||v===undefined)return 'Not specified';if(typeof v==='object')return Array.isArray(v)?v.map(format).join(' · '):Object.entries(v).map(([k,x])=>human(k)+': '+format(x)).join('; ');return String(v);}
function detail(title,value){const d=node('details');d.append(node('summary',title));if(typeof value==='string'){d.append(node('p',value));return d;}if(Array.isArray(value))d.append(list(value));else{const dl=node('dl');for(const [k,v] of Object.entries(value||{})){dl.append(node('dt',human(k)),node('dd',format(v)));}d.append(dl);}return d;}
function section(id,title){let s=$(id);if(!s){s=node('section',undefined,'record-section');s.id=id;$('review-body').insertBefore(s,$('gaps'));}s.append(node('h2',title));return s;}
try{
 const id=new URLSearchParams(location.search).get('id');if(!/^[a-z0-9-]+$/.test(id||''))throw Error('Select a reviewed paper from the source library.');
 const response=await fetch('data/paper-reviews/'+id+'.json');if(!response.ok)throw Error('Full-document review has not yet been published for this paper.');const c=await response.json();
 $('review-title').textContent=c.title;document.title=c.title+' · Source review | MatterSyn';$('review-doi').textContent=c.doi;$('review-doi').href='https://doi.org/'+c.doi;
 const total=c.documents.reduce((n,d)=>n+d.page_count,0);$('review-summary').textContent=`${c.review_scope_label||'Supplied-document review'} · ${total} pages read and visually checked · ${c.figures.length} original figures · ${c.tables?.length||0} tables inventoried. Complete source reading does not fill information omitted by the authors.`;
 $('review-download').href='data/paper-reviews/'+id+'.json';$('review-download').download=id+'-paper-coverage.json';
 const docs=section('documents','Supplied documents and review scope');
 if(c.supporting_information)docs.append(detail('Supporting-information availability',c.supporting_information));
 docs.append(node('p','Independent extraction audit: '+human(c.independent_audit||'pending')));if(c.audit_details)docs.append(detail('Audit scope and corrections',{scope:c.audit_details}));
 if(c.main_si_match||c.document_identity_verification)docs.append(detail(c.main_si_match?'Main–SI identity verification':'Document identity verification',c.main_si_match||c.document_identity_verification));
 for(const d of c.documents){const card=node('article',undefined,'paper-contribution');card.append(node('h3',human(d.role)+' · '+d.page_count+' pages'),node('p',d.source_file||d.filename||''));const rows=node('div',undefined,'review-page-list');for(const p of d.pages){const row=node('p');row.append(node('strong','Page '+p.page+' · '),node('span','Text read · Visual review · '+(p.sections||[]).join('; ')));if(p.unresolved?.length)row.append(node('small','Open details: '+p.unresolved.join('; ')));rows.append(row);}card.append(rows,detail('Source fingerprint',{sha256:d.sha256}));docs.append(card);}
 const recipes=section('recipes','Synthesis variants, controls and procedures');
 recipes.append(node('p','Variants, aliquots, controls and shared procedures are distinct record types. Their count is not the number of independent experimental runs.'));
 for(const r of c.recipe_inventory){const card=node('article',undefined,'paper-contribution');card.append(node('span',human(r.status),'atlas-status'),node('h3',r.label||r.id));if(r.record_type)card.append(node('p',human(r.record_type),'mini-label'));if(r.scope)card.append(node('p',r.scope));for(const rid of r.record_ids||[])card.append(link('Inspect '+rid+' →','records/'+rid+'.html'));card.append(node('p',format(r.source_locators||[])));if(r.gaps?.length)card.append(detail('Unreported or unresolved information',r.gaps));recipes.append(card);}
 const chars=section('characterization','Characterization and properties');const characterization=c.characterization_inventory||[];if(characterization.reader_item_ids){const items=new Map((c.reader_sections||[]).flatMap(s=>s.items||[]).map(x=>[x.id,x]));for(const id of characterization.reader_item_ids){const item=items.get(id);if(item){const p=node('p');p.append(link(item.title,'#evidence-'+id));chars.append(p);}}}else for(const x of characterization){const card=node('article',undefined,'paper-contribution');card.append(node('h3',x.technique||x.name||'Measurement'));const fields={...x};delete fields.technique;delete fields.name;for(const [k,v]of Object.entries(fields))card.append(node('p',human(k)+': '+format(v)));chars.append(card);}
 const figures=section('figures','Original figures and sample assignments');figures.append(node('p','Open a figure to inspect the original axes, panel labels and scale bars. Continuous curves are not represented as raw numerical data unless a separate digitization is documented.'));
 const grid=node('div',undefined,'review-figure-grid');
 for(const f of c.figures){const card=node('article',undefined,'review-figure');const a=link('',f.public_asset);a.className='review-image-link';a.dataset.figure=f.public_asset;a.dataset.title=f.label||f.id||'Original figure';const im=document.createElement('img');im.src=f.public_asset;im.alt=f.caption_paraphrase||f.label||f.id;im.loading='lazy';a.append(im);card.append(a,node('h3',f.label||f.id||'Figure'),node('p',f.caption_paraphrase||f.description||''));card.append(node('small',(f.document_role||'Source')+' · PDF page '+(f.page||f.pdf_page||f.original_crop_asset?.pdf_page||'?')));if(f.sample_links?.length)card.append(detail('Sample and recipe assignments',f.sample_links));if(f.sample_linkage)card.append(node('p','Sample linkage: '+f.sample_linkage));for(const k of ['sample_scope','panels','quantitative_facts','quantitative_context','limitations','quantitative_extraction','notes','unresolved','source_locators'])if(f[k])card.append(typeof f[k]==='object'?detail(human(k),f[k]):node('p',f[k]));grid.append(card);}figures.append(grid);
 for(const [key,title]of [['tables','Tables'],['schemes','Schemes'],['equations','Equations and model assumptions'],['source_notes','Source notes'],['simulation_inventory','Simulation model and assumptions']]){const items=Array.isArray(c[key])?c[key]:c[key]?[c[key]]:[];if(!items.length)continue;const s=section(key,title);for(const x of items){if(x.public_asset){const a=link('Open original '+(x.label||x.id)+' ↗',x.public_asset);a.dataset.figure=x.public_asset;a.dataset.title=x.label||x.id;s.append(a);}s.append(detail(x.id||x.label||x.title||title,x));}}
 for(const [key,title] of [['materials_inventory','Additional reagent and acquisition materials'],['conditioning','Reagent and apparatus conditioning']]){const value=c[key];if(value){const host=section(key,title);host.append(detail(title,value));}}
 if(c.reader_sections?.length){const source=section('source-evidence','Source evidence');mountSourceSections(source,c);}
 const gaps=section('gaps','Source conflicts and unresolved information');gaps.append(list(c.evidence_conflicts||[]),list(c.remaining_gaps||[]));const refs=c.referenced_methods||c.referenced_methods_not_locally_resolved||c.unresolved_referenced_methods;if(refs?.length)gaps.append(detail('Referenced methods and follow-up reading',refs));
 const dialog=$('figure-dialog');$('figure-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close();};document.addEventListener('click',e=>{const a=e.target.closest('[data-figure]');if(!a)return;e.preventDefault();$('figure-title').textContent=a.dataset.title;$('figure-large').src=a.dataset.figure;$('figure-large').alt=a.dataset.title;dialog.showModal();});
 if(location.hash)document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView({block:'start'});
}catch(e){$('review-summary').textContent=e.message;console.error(e);}
