const $=id=>document.getElementById(id),id=new URLSearchParams(location.search).get('id');
function node(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;}
function link(text,url){const a=node('a',text);a.href=url;return a;}
try{if(!/^paper-[a-f0-9]+$/.test(id||''))throw Error('Select a paper from the source library.');const res=await fetch('data/papers/'+id+'.json',{cache:'no-store'});if(!res.ok)throw Error('Paper record not found.');const p=await res.json();document.title=(p.title||p.doi)+' · MatterSyn';$('paper-title').textContent=p.title||'Title awaiting verification';$('paper-doi').textContent=p.doi;$('paper-doi').href=p.doiUrl;
 $('paper-review').textContent=p.fullDocumentReview?(p.fullDocumentReview.label||'Supplied-document review')+'. Experimental omissions remain explicit.':p.reviewStatus==='selected_recipes_reviewed'?'Selected recipes reviewed; full-paper coverage remains source-specific.':p.reviewStatus==='published_benchmark'?'Published numerical benchmark; row verification does not reconstruct complete protocols.':'Indexed automatically. Detailed recipe and figure review is pending.';
 $('paper-title-status').textContent=p.titleVerifiedFromSelectedRecord?'Title checked against a reviewed source record.':'Bibliographic title candidate: '+(p.titleMetadata?.origin||'metadata')+'; '+(p.titleMetadata?.confidence||'unverified')+' confidence.';
 if(p.fullDocumentReview)$('paper-full-review').append(link('Open full review · '+p.fullDocumentReview.pages+' pages · '+p.fullDocumentReview.figures+' original figures →',p.fullDocumentReview.url));
 const c=p.coverage;$('paper-coverage').textContent=`Local documents: ${c.localDocumentCount??'not in bulk snapshot'} · Main candidate: ${c.mainDocumentAvailable?'present':'not linked'} · SI candidate: ${c.supportingDocumentAvailable?'present':'not linked'}. Filename grouping is not proof of a matching supplement.`;
 $('paper-extraction').textContent=Object.entries(c.extractionStatusCounts||{}).map(([k,v])=>k.replaceAll('_',' ')+': '+v).join(' · ')+(c.mainSupportingExactDuplicate?' · Main/SI files include an exact-content duplicate.':'')+(c.documentRoleMismatchCount?' · '+c.documentRoleMismatchCount+' document(s) have a filename/heading role mismatch.':'');
 const host=$('paper-records');for(const rid of [...p.reviewedRecordIds,...p.benchmarkRecordIds]){const line=node('p','');line.append(link(rid,'records/'+rid+'.html'));host.append(line);}if(!host.children.length)host.append(node('p','No reviewed training record has been created for this paper yet.'));
 const index=await (await fetch('data/materials-index.json',{cache:'no-store'})).json();for(const formula of p.materials){const m=index.materials.find(m=>m.formula===formula);if(m){const line=node('p','');line.append(link(m.formula+' · '+m.name,m.url));$('paper-materials').append(line);}}
 if(!$('paper-materials').children.length)$('paper-materials').append(node('p','No verified synthesis contribution has been assigned to a published material page. This paper remains searchable for review.'));
 $('paper-source-note').textContent='Full text and page-linked extraction candidates are retained in the local research corpus. This public page provides bibliographic provenance and review status; it does not redistribute the full paper or infer experimental labels from automatic extraction.';
}catch(e){$('paper-review').textContent=e.message;console.error(e);}
