import {buildPati2009Scene,createPati2009Art,createPati2009ConditionGrid} from './pati2009-protocol.mjs';
import {buildMatuhina2023Scene,createMatuhina2023Art,createMatuhina2023ConditionGrid} from './matuhina2023-protocol.mjs';
import {buildSommer2020Scene,createSommer2020Art,createSommer2020ConditionGrid} from './sommer2020-protocol.mjs';
import {buildGhosh2012Scene,createGhosh2012Art,createGhosh2012ConditionGrid} from './ghosh2012-protocol.mjs';
import {buildLian2021Scene,createLian2021Art,createLian2021ConditionGrid} from './lian2021-protocol.mjs';
import {buildMorrison2017Scene,createMorrison2017Art,createMorrison2017ConditionGrid} from './morrison2017-protocol.mjs';
import {buildEvans2010Scene,createEvans2010Art,createEvans2010ConditionGrid} from './evans2010-protocol.mjs';
import {buildHeo2003Scene,createHeo2003Art,createHeo2003ConditionGrid} from './heo2003-protocol.mjs';
import {buildNagasaki2004Scene,createNagasaki2004Art} from './nagasaki2004-protocol.mjs';
import {buildRibeiro2004Scene,createRibeiro2004Art} from './ribeiro2004-protocol.mjs';
import {buildNorberg2004Scene,createNorberg2004Art} from './norberg2004-protocol.mjs';
import {buildGu2004Scene,createGu2004Art} from './gu2004-protocol.mjs';
import {buildSashchiuk2004Scene,createSashchiuk2004Art} from './sashchiuk2004-protocol.mjs';
import {buildSchwartz2003Scene,createSchwartz2003Art} from './schwartz2003-protocol.mjs';
import {buildBanerjee2003Scene,createBanerjee2003Art} from './banerjee2003-protocol.mjs';
import {buildYi2002Scene,createYi2002Art} from './yi2002-protocol.mjs';
import {buildDantas2002Scene,createDantas2002Art} from './dantas2002-protocol.mjs';
import {buildBesson2002Scene,createBesson2002Art} from './besson2002-protocol.mjs';
import {buildBraun2001Scene,createBraun2001Art} from './braun2001-protocol.mjs';
import {buildGerion2001Scene,createGerion2001Art} from './gerion2001-protocol.mjs';
import {buildShah2001Scene,createShah2001Art} from './shah2001-protocol.mjs';
import {buildPeng1998Scene,createPeng1998Art} from './peng1998-protocol.mjs';
import {quantityValue} from './quantity-value.mjs';
import {buildStigerScene,createStigerArt} from './stiger-protocol.mjs';
import {buildYaoScene,createYaoArt} from './yao-protocol.mjs';
import {buildVeinotScene,createVeinotArt} from './veinot-protocol.mjs';
import {buildAerosolScene,createAerosolArt,createAerosolConditionGrid} from './aerosol-protocol.mjs';
import {createAnalysisArt} from './analysis-protocol.mjs';
import {buildWaferScene,createWaferArt} from './wafer-protocol.mjs';
import {buildDanekScene,createDanekArt} from './danek-protocol.mjs';
import {buildDabbousiScene,createDabbousiArt} from './dabbousi-protocol.mjs';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let diagramDialog;
function expandDiagram(svg,label){
 if(!diagramDialog){diagramDialog=el('dialog',undefined,'protocol-diagram-dialog');document.body.append(diagramDialog);}
 const head=el('header'),close=el('button','Close ×'),pan=el('div',undefined,'diagram-pan'),controls=el('div',undefined,'protocol-controls');close.type='button';close.onclick=()=>diagramDialog.close();head.append(el('h2',label),close);pan.innerHTML=svg.outerHTML;let scale=1;
 for(const [label,factor] of [['−',1/1.25],['Reset',0],['+',1.25]]){const b=el('button',label);b.type='button';b.onclick=()=>{scale=factor?Math.max(.5,Math.min(4,scale*factor)):1;pan.querySelector('svg').style.width=(100*scale)+'%';};controls.append(b);}
 diagramDialog.replaceChildren(head,pan,controls,el('p','Source-specific operation diagram. Geometry is illustrative; original experimental data are shown separately.'));diagramDialog.showModal();
}
const human=s=>String(s||'').replaceAll('_',' ');
function amount(q){if(!q)return 'Not reported';if(q.raw_text==='approximately one-third its original volume')return 'Approximately one-third of original volume';const value=quantityValue(q);if(value===null&&q.unit==='degC'&&/^room temperature\b/i.test(q.qualifier||''))return 'Room temperature (numeric value not reported)'+(q.basis?' · '+q.basis:'');const unit=({degC:'°C',angstrom:'Å',um:'µm',umol:'µmol',uL:'µL',uM:'µM',uJ:'µJ'})[q.unit]||q.unit||'';return (value===null?'Not reported':`${q.approximate?'≈':''}${value} ${unit}`)+(q.qualifier?' · '+q.qualifier:'')+(q.basis?' · '+q.basis:'');}
function fact(f){return f?.value||f?.note||'Not reported';}
function kind(o){const a=o.action.toLowerCase();if(/store/.test(a))return 'store';if(/filter/.test(a))return 'filter';if(/centrifug|purif|wash|rinse|precipitat|floccul|nonsolvent/.test(a))return 'separate';if(/dry|evaporat|distill/.test(a))return 'dry';if(/cool|quench|remove_heat/.test(a))return 'cool';if(/inject|hot_add/.test(a))return 'inject';if(/sample|measur|aliquot|drop_cast/.test(a))return 'sample';if(/degas|vacuum|evacuat|freeze|gas_saturate/.test(a))return 'degas';if(/heat|grow|react|stabilize/.test(a))return 'heat';return 'prepare';}
function vial(label){const n=el('div',undefined,'scene-vial clear');n.innerHTML='<div class="sv-cap"></div><div class="sv-glass"><div class="sv-liquid"></div></div>';n.append(el('span',label));return n;}
function art(o,r,prefix){const sourceArt=createPati2009Art(o,r)||createMatuhina2023Art(o,r)||createSommer2020Art(o,r)||createGhosh2012Art(o,r)||createLian2021Art(o,r)||createMorrison2017Art(o,r)||createEvans2010Art(o,r)||createHeo2003Art(o,r)||createNagasaki2004Art(o,r)||createRibeiro2004Art(o,r)||createNorberg2004Art(o,r)||createGu2004Art(o,r)||createSashchiuk2004Art(o,r)||createSchwartz2003Art(o,r)||createBanerjee2003Art(o,r)||createYi2002Art(o,r)||createDantas2002Art(o,r)||createBesson2002Art(o,r)||createBraun2001Art(o,r)||createGerion2001Art(o,r)||createShah2001Art(o,r)||createPeng1998Art(o,r)||createStigerArt(o,r)||createYaoArt(o,r)||createVeinotArt(o,r)||createDabbousiArt(o,r)||createDanekArt(o,r)||createWaferArt(o,r,prefix)||createAerosolArt(o,r,prefix)||createAnalysisArt(o,r);if(sourceArt)return sourceArt;const type=kind(o),host=el('div',undefined,'protocol-art protocol-art-'+type);host.dataset.scene=type;host.setAttribute('role','img');host.setAttribute('aria-label',`${human(type)} operation schematic: ${o.label}`);
 const names=new Map([...r.materials.map(x=>[x.id,x.name]),...r.stocks.map(x=>[x.id,x.name]),...r.material_states.map(x=>[x.id,x.label||x.name||x.id])]);
 if(['heat','degas','inject'].includes(type)){host.insertAdjacentHTML('beforeend','<svg class="neutral-reaction-vessel" viewBox="0 0 250 310" aria-hidden="true"><path d="M101 22H149V119C207 137 232 195 205 240C177 286 73 286 45 240C18 195 43 137 101 119Z" fill="#e5f3fa" fill-opacity=".6" stroke="#7899ad" stroke-width="3"/><path d="M44 204C86 216 162 217 206 204C211 265 48 291 44 204Z" fill="#d6b66f" fill-opacity=".58"/><path d="M107 30V129C68 145 51 178 55 202M73 247C81 252 89 255 99 257" fill="none" stroke="white" stroke-width="7" stroke-linecap="round"/><ellipse cx="125" cy="22" rx="27" ry="6" fill="#f8fcff" stroke="#7899ad" stroke-width="2"/><ellipse cx="125" cy="207" rx="80" ry="12" fill="#e3c77f" fill-opacity=".6"/><path d="M112 244H139" stroke="#748f9e" stroke-width="7" stroke-linecap="round"/></svg>');
  if(type==='inject')host.insertAdjacentHTML('beforeend','<div class="scene-syringe" aria-hidden="true"><div class="plunger-top"></div><div class="plunger-stem"></div><div class="syringe-barrel"><i></i></div><div class="syringe-needle"></div></div>');
  else if(/bath/i.test(o.description)){host.insertAdjacentHTML('beforeend','<div class="heating-bath" aria-hidden="true"><div class="bath-rim"></div><div class="bath-front"></div><div class="heater-base"><i></i><span>HEATING</span><b></b></div></div>');}
  else if(type==='heat'||Object.keys(o.parameters).some(k=>/temperature/.test(k)))host.insertAdjacentHTML('beforeend','<div class="schematic-heater"><span>HEATING</span><i></i></div>');
  if(type==='degas')host.append(el('div',fact(o.environment),'protocol-atmosphere'));
 }else if(type==='separate'){host.append(vial('Separation'),vial('Recovered fraction'));host.insertAdjacentHTML('beforeend','<div class="mini-centrifuge" aria-hidden="true"><div class="rotor"><i></i><i></i><i></i><i></i></div><span>SEPARATION</span></div>');if(!/centrifug/i.test(o.action+' '+o.description))host.querySelector('.mini-centrifuge').remove();
 }else if(type==='dry'){host.insertAdjacentHTML('beforeend','<div class="drying-dish"><div></div><span>Recovered material</span></div>');}
 else if(type==='filter'){host.innerHTML='<svg viewBox="0 0 300 270" aria-hidden="true"><path d="M65 35H235L164 135V175L138 185V135Z" fill="#f0f7fc" stroke="#7e9bac" stroke-width="3"/><path d="M103 201V244Q150 261 197 244V201" fill="#d6eaf4" stroke="#7e9bac" stroke-width="3"/><path d="M72 49L151 121L228 49" fill="none" stroke="#d8b671" stroke-width="3"/><path d="M151 190V211" stroke="#72a8bc" stroke-dasharray="3 6" stroke-width="4"/></svg>';}
 else{const labels=type==='prepare'?o.inputs.map(x=>names.get(x)||human(x)).slice(0,3):[type==='cool'?'Reaction mixture':type==='sample'?'Aliquot / specimen':'Stored material'];for(const label of labels.length?labels:['Preparation'])host.append(vial(label));if(type==='cool')host.append(el('div','↓','cooling-symbol'));if(type==='sample')host.append(el('div','→','sample-symbol'));}
 host.append(el('span',human(type),'protocol-art-label'));return host;
}
export function mountProtocol(host,r,prefix=''){
 if(!host||!r.operations.length)return;host.replaceChildren();host.classList.add('illustrated-protocol');
 const bar=el('div',undefined,'protocol-step-list');bar.setAttribute('aria-label','Protocol stages');const display=el('div',undefined,'protocol-stage');host.append(bar,display);let selected=0;
 const buttons=r.operations.map((o,i)=>{const b=el('button',`${String(i+1).padStart(2,'0')}  ${o.label}`);b.type='button';b.addEventListener('click',()=>render(i));bar.append(b);return b;});
 function render(i){selected=i;const o=r.operations[i];buttons.forEach((b,j)=>{b.setAttribute('aria-pressed',String(j===i));b.classList.toggle('active',j===i);});display.replaceChildren();
  const pati=buildPati2009Scene(o,r),matuhina=buildMatuhina2023Scene(o,r),sommer=buildSommer2020Scene(o,r),ghosh=buildGhosh2012Scene(o,r),lian=buildLian2021Scene(o,r),morrison=buildMorrison2017Scene(o,r),evans=buildEvans2010Scene(o,r),heo=buildHeo2003Scene(o,r),aerosol=buildAerosolScene(o,r),wafer=buildWaferScene(o,r),danek=buildDanekScene(o,r),dabbousi=buildDabbousiScene(o,r),veinot=buildVeinotScene(o,r),yao=buildYaoScene(o,r),stiger=buildStigerScene(o,r),peng=buildPeng1998Scene(o,r),shah=buildShah2001Scene(o,r),gerion=buildGerion2001Scene(o,r),braun=buildBraun2001Scene(o,r),besson=buildBesson2002Scene(o,r),dantas=buildDantas2002Scene(o,r),yi=buildYi2002Scene(o,r),banerjee=buildBanerjee2003Scene(o,r),schwartz=buildSchwartz2003Scene(o,r),sashchiuk=buildSashchiuk2004Scene(o,r),gu=buildGu2004Scene(o,r),nagasaki=buildNagasaki2004Scene(o,r),ribeiro=buildRibeiro2004Scene(o,r),norberg=buildNorberg2004Scene(o,r);
  const visual=el('div',undefined,'protocol-visual'),copy=el('div',undefined,'protocol-copy');visual.append(art(o,r,prefix),el('p',pati?.caption||matuhina?.caption||sommer?.caption||ghosh?.caption||lian?.caption||morrison?.caption||evans?.caption||heo?.caption||nagasaki?.caption||ribeiro?.caption||norberg?.caption||gu?.caption||sashchiuk?.caption||schwartz?.caption||banerjee?.caption||yi?.caption||dantas?.caption||besson?.caption||braun?.caption||gerion?.caption||shah?.caption||peng?.caption||stiger?.caption||yao?.caption||veinot?.caption||dabbousi?.caption||danek?.caption||wafer?.caption||aerosol?.caption||'Operation schematic. Vessel geometry and liquid colors are illustrative; source-reported equipment and conditions are specified alongside.','protocol-visual-note'));
  if(pati||matuhina||sommer||ghosh||lian||morrison||evans||heo||nagasaki||ribeiro||norberg){const expand=el('button','Enlarge operation diagram ↗','molecule-link');expand.type='button';expand.onclick=()=>expandDiagram(visual.querySelector('svg'),o.label);visual.append(expand);}
  copy.append(el('span',`${String(i+1).padStart(2,'0')} / ${r.operations.length} · ${human(o.stage)}${o.optional?' · optional branch':''}`,'mini-label'),el('h3',o.label),el('p',o.description));
  const dl=pati?createPati2009ConditionGrid(o,r):matuhina?createMatuhina2023ConditionGrid(o,r):sommer?createSommer2020ConditionGrid(o,r):ghosh?createGhosh2012ConditionGrid(o,r):lian?createLian2021ConditionGrid(o,r):morrison?createMorrison2017ConditionGrid(o,r):evans?createEvans2010ConditionGrid(o,r):heo?createHeo2003ConditionGrid(o,r):aerosol?createAerosolConditionGrid(o,r):el('dl',undefined,'protocol-condition-grid');const entries=Object.entries(o.parameters);if(!aerosol&&!heo&&!evans&&!morrison&&!lian&&!ghosh&&!sommer&&!matuhina&&!pati)for(const [key,label] of [['temperature','Temperature'],['duration|time','Duration'],['pressure','Pressure']]){const match=entries.find(([k])=>new RegExp(key).test(k.toLowerCase()));const variants=!match&&key==='temperature'&&danek&&['composite','cap-layer'].includes(o.id)?(r.condition_options||[]).map(c=>c.parameters?.substrate_temperature).filter(Boolean):[];const item=el('div');item.append(el('dt',variants.length?'Substrate temperature (reported variants)':match?human(match[0]):label),el('dd',variants.length?[...new Set(variants.map(v=>amount(v)))].join(' / ')+'; see condition sets':dabbousi&&key==='temperature'&&['heat-seeds','dose'].includes(o.id)&&(r.condition_options||[]).some(c=>c.parameters?.input_core_diameter&&c.parameters?.overgrowth_temperature)?'See source-paired temperatures below':amount(match?.[1])));dl.append(item);}if(!heo&&!evans&&!morrison&&!lian&&!ghosh&&!sommer&&!matuhina&&!pati){const env=el('div');env.append(el('dt','Environment'),el('dd',fact(o.environment)));dl.append(env);}copy.append(dl);
  if(aerosol)for(const note of aerosol.notes)copy.append(el('p',note,'record-note'));
  if(wafer)for(const note of wafer.notes)copy.append(el('p',note,'record-note'));
  if(danek||dabbousi||veinot||yao||stiger||peng||shah||gerion||braun||besson||dantas||yi||banerjee||schwartz||sashchiuk||gu||nagasaki||ribeiro||norberg){const extra=el('dl',undefined,'protocol-condition-grid');for(const [k,v]of entries.filter(([k])=>(gerion||braun||besson||dantas||yi||banerjee||schwartz||sashchiuk||gu||nagasaki||ribeiro||norberg)?!['temperature','duration|time','pressure'].some(pattern=>entries.find(([name])=>new RegExp(pattern).test(name.toLowerCase()))?.[0]===k):/flow|rate|voltage|thickness|concentration|pore_size|beam_energy|accelerating_voltage|volume|path|count|photon_energy|power|current|slit|resolution|q_range|reported_distance|frequency|mesh|drops|line_density|sieve_pore|remaining_volume|duration_threshold|potential|electrode_area|camera_length|aperture|scan_width|scan_height|fields_per_sample|wavelength|two_theta|eluent_pH|diameter|depth/.test(k))){const item=el('div');item.append(el('dt',human(k)),el('dd',amount(v)));extra.append(item);}if(extra.children.length)copy.append(extra);}
  if(dabbousi&&['heat-seeds','dose'].includes(o.id)){const pairs=(r.condition_options||[]).filter(c=>c.parameters?.input_core_diameter&&c.parameters?.overgrowth_temperature);if(pairs.length){copy.append(el('p','Source-reported input core diameter → overgrowth temperature (Note 22). Discrete alternatives; no interpolation.','record-note'));const pairList=el('dl',undefined,'protocol-condition-grid');for(const c of pairs){const row=el('div');row.append(el('dt',amount(c.parameters.input_core_diameter)),el('dd',amount(c.parameters.overgrowth_temperature)));pairList.append(row);}copy.append(pairList);}}
  const more=el('details'),summary=el('summary','All reported conditions and source');more.append(summary);for(const [k,v] of entries)more.append(el('p',human(k)+': '+amount(v)));more.append(el('p','Endpoint: '+fact(o.endpoint)));if(o.retained_fraction)more.append(el('p','Retained fraction: '+human(o.retained_fraction)));for(const e of o.evidence)more.append(el('small',`${e.source_id} · ${e.locator}`));copy.append(more);
  const controls=el('div',undefined,'protocol-controls');const prev=el('button','← Previous'),next=el('button','Next →');prev.type=next.type='button';prev.disabled=i===0;next.disabled=i===r.operations.length-1;prev.onclick=()=>render(selected-1);next.onclick=()=>render(selected+1);controls.append(prev,next);copy.append(controls);display.append(visual,copy);
 }
 render(0);
}
